apiVersion: v1
kind: Service
metadata:
  name: event-service
  labels:
    app.kubernetes.io/name: event-hub
    app.kubernetes.io/component: event-service
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: event-hub
    app.kubernetes.io/component: event-service
  ports:
    - name: http
      port: 3000
      targetPort: http
      protocol: TCP
