apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - default-deny-ingress.yaml
  - allow-router-to-frontend.yaml
  - allow-frontend-to-gateway.yaml
  - allow-gateway-to-domain-services.yaml
  - allow-registration-to-event.yaml
  - allow-service-to-own-db.yaml
