apiVersion: v1
kind: Service
metadata:
  name: db-users
  labels:
    app.kubernetes.io/name: event-hub
    app.kubernetes.io/component: db-users
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/name: event-hub
    app.kubernetes.io/component: db-users
  ports:
    - name: postgres
      port: 5432
      targetPort: postgres
      protocol: TCP
